---

services:
  postgres:
    # this is postgres with the pg_duckdb extension precompiled
    # https://pgxman.com/x/pg_duckdb
    # https://github.com/duckdb/pg_duckdb
    image: pgduckdb/pgduckdb:18-main
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-deframer}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-deframer}
      POSTGRES_DB: ${POSTGRES_DB:-deframer}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - infra-env-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-deframer}"]
      interval: 10s
      timeout: 5s
      retries: 10

  ready-check:
    image: alpine:latest
    depends_on:
      postgres:
        condition: service_healthy
    command: |
      sh -c "'echo SUCCESS: infra-env initialized'"

networks:
  infra-env-net:
    name: deframer-infra-env-net

volumes:
  postgres_data:
