---
services:
  postgres:
    # this is postgres with the pg_duckdb extension precompiled
    # https://pgxman.com/x/pg_duckdb
    # https://github.com/duckdb/pg_duckdb
    image: pgduckdb/pgduckdb:18-main
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-deframer}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-deframer}
      POSTGRES_DB: ${POSTGRES_DB:-deframer}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-deframer}"]
      interval: 5s
      timeout: 5s
      retries: 5

  service:
    image: ghcr.io/deframer/news-deframer/service:latest
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PORT=${PORT:-8080}
      - DSN=${DSN:-host=postgres user=deframer password=deframer dbname=deframer port=5432 sslmode=disable}
      - LOG_DATABASE=${LOG_DATABASE:-false}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - BASIC_AUTH_USER=${BASIC_AUTH_USER:-}
      - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD:-}
    ports:
      - "${PORT:-8080}:${PORT:-8080}"

  worker:
    image: ghcr.io/deframer/news-deframer/worker:latest
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DSN=${DSN:-host=postgres user=deframer password=deframer dbname=deframer port=5432 sslmode=disable}
      - LOG_DATABASE=${LOG_DATABASE:-false}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LLM_TYPE=${LLM_TYPE:-}
      - LLM_MODEL=${LLM_MODEL:-}
      - LLM_API_KEY=${LLM_API_KEY:-}
      - LLM_BASE_URL=${LLM_BASE_URL:-}

  miner:
    image:  ghcr.io/deframer/news-deframer-mining/miner:latest
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DSN=${DSN:-host=postgres user=deframer password=deframer dbname=deframer port=5432 sslmode=disable}
      - LOG_DATABASE=${LOG_DATABASE:-false}
      - LOG_LEVEL=${LOG_LEVEL:-info}

volumes:
  postgres_data:
