---

services:
  rssbridge:
    image: rssbridge/rss-bridge
    ports:
      - "8002:80"
    restart: unless-stopped
    volumes:
      - ./config:/config
      - ./bridges/SpiegelBridge.php:/app/bridges/SpiegelBridge.php
      - ./bridges/TagesschauBridge.php:/app/bridges/TagesschauBridge.php
    networks:
      - test-env-network

# TODO: we might want a selenium/webdriver here

networks:
  test-env-network:
    external: true
    name: deframer-test-env-net
